import Head from 'next/head'
import {useRouter} from 'next/router';

const Dyno = () => {
    const router = useRouter();
    return (
        <div>
            <Head>
                <title>{router.query.id}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
           <div>Page {router.query.id}</div> 
        </div>
    )
}

export default Dyno;